apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosaga.fullname" . }}-api
  labels:
    {{- include "gosaga.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "gosaga.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
