// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: proto/liveness.proto

package livenesspb

/*
MIT License

Copyright (c) 2026 Bugs5382

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*WorkerEvent_Start
	//	*WorkerEvent_Heartbeat
	//	*WorkerEvent_Complete
	//	*WorkerEvent_Error
	Event isWorkerEvent_Event `protobuf_oneof:"event"`
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{0}
}

func (m *WorkerEvent) GetEvent() isWorkerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *WorkerEvent) GetStart() *StartJob {
	if x, ok := x.GetEvent().(*WorkerEvent_Start); ok {
		return x.Start
	}
	return nil
}

func (x *WorkerEvent) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetEvent().(*WorkerEvent_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *WorkerEvent) GetComplete() *Complete {
	if x, ok := x.GetEvent().(*WorkerEvent_Complete); ok {
		return x.Complete
	}
	return nil
}

func (x *WorkerEvent) GetError() *Error {
	if x, ok := x.GetEvent().(*WorkerEvent_Error); ok {
		return x.Error
	}
	return nil
}

type isWorkerEvent_Event interface {
	isWorkerEvent_Event()
}

type WorkerEvent_Start struct {
	Start *StartJob `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type WorkerEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerEvent_Complete struct {
	Complete *Complete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"`
}

type WorkerEvent_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*WorkerEvent_Start) isWorkerEvent_Event() {}

func (*WorkerEvent_Heartbeat) isWorkerEvent_Event() {}

func (*WorkerEvent_Complete) isWorkerEvent_Event() {}

func (*WorkerEvent_Error) isWorkerEvent_Event() {}

type StartJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId   string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId  string `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Attempt int32  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
}

func (x *StartJob) Reset() {
	*x = StartJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJob) ProtoMessage() {}

func (x *StartJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJob.ProtoReflect.Descriptor instead.
func (*StartJob) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{1}
}

func (x *StartJob) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartJob) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StartJob) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgressPct int32  `protobuf:"varint,1,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	Note        string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *Heartbeat) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Complete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultJson []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// If non-empty, this was a dry-run; structured "what would change".
	WouldChangeJson []byte `protobuf:"bytes,2,opt,name=would_change_json,json=wouldChangeJson,proto3" json:"would_change_json,omitempty"`
}

func (x *Complete) Reset() {
	*x = Complete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Complete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complete) ProtoMessage() {}

func (x *Complete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complete.ProtoReflect.Descriptor instead.
func (*Complete) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{3}
}

func (x *Complete) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *Complete) GetWouldChangeJson() []byte {
	if x != nil {
		return x.WouldChangeJson
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable bool   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type EngineEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*EngineEvent_Ack
	//	*EngineEvent_Cancel
	Event isEngineEvent_Event `protobuf_oneof:"event"`
}

func (x *EngineEvent) Reset() {
	*x = EngineEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineEvent) ProtoMessage() {}

func (x *EngineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineEvent.ProtoReflect.Descriptor instead.
func (*EngineEvent) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{5}
}

func (m *EngineEvent) GetEvent() isEngineEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EngineEvent) GetAck() *Acknowledged {
	if x, ok := x.GetEvent().(*EngineEvent_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *EngineEvent) GetCancel() *CancelRequested {
	if x, ok := x.GetEvent().(*EngineEvent_Cancel); ok {
		return x.Cancel
	}
	return nil
}

type isEngineEvent_Event interface {
	isEngineEvent_Event()
}

type EngineEvent_Ack struct {
	Ack *Acknowledged `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type EngineEvent_Cancel struct {
	Cancel *CancelRequested `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*EngineEvent_Ack) isEngineEvent_Event() {}

func (*EngineEvent_Cancel) isEngineEvent_Event() {}

type Acknowledged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Acknowledged) Reset() {
	*x = Acknowledged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledged) ProtoMessage() {}

func (x *Acknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledged.ProtoReflect.Descriptor instead.
func (*Acknowledged) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{6}
}

type CancelRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CancelRequested) Reset() {
	*x = CancelRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_liveness_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequested) ProtoMessage() {}

func (x *CancelRequested) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liveness_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequested.ProtoReflect.Descriptor instead.
func (*CancelRequested) Descriptor() ([]byte, []int) {
	return file_proto_liveness_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequested) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_liveness_proto protoreflect.FileDescriptor

var file_proto_liveness_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x22,
	0xce, 0x01, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4a, 0x6f,
	0x62, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x2f,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x54, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x15, 0x0a, 0x06,
	0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75,
	0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61,
	0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x22, 0x42, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f,
	0x70, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x50, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x57, 0x0a, 0x08, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x77, 0x6f, 0x75, 0x6c, 0x64,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0f, 0x77, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4a,
	0x73, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x74, 0x72, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x75, 0x0a, 0x0b, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x06,
	0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x0e, 0x0a, 0x0c, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x22,
	0x29, 0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x4f, 0x0a, 0x0e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a, 0x0b,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x74, 0x65, 0x70, 0x12, 0x14, 0x2e, 0x73, 0x61,
	0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x1a, 0x14, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x43, 0x5a, 0x41, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x6f,
	0x72, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x61, 0x67,
	0x61, 0x2d, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_liveness_proto_rawDescOnce sync.Once
	file_proto_liveness_proto_rawDescData = file_proto_liveness_proto_rawDesc
)

func file_proto_liveness_proto_rawDescGZIP() []byte {
	file_proto_liveness_proto_rawDescOnce.Do(func() {
		file_proto_liveness_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_liveness_proto_rawDescData)
	})
	return file_proto_liveness_proto_rawDescData
}

var file_proto_liveness_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_liveness_proto_goTypes = []any{
	(*WorkerEvent)(nil),     // 0: saga.v1.WorkerEvent
	(*StartJob)(nil),        // 1: saga.v1.StartJob
	(*Heartbeat)(nil),       // 2: saga.v1.Heartbeat
	(*Complete)(nil),        // 3: saga.v1.Complete
	(*Error)(nil),           // 4: saga.v1.Error
	(*EngineEvent)(nil),     // 5: saga.v1.EngineEvent
	(*Acknowledged)(nil),    // 6: saga.v1.Acknowledged
	(*CancelRequested)(nil), // 7: saga.v1.CancelRequested
}
var file_proto_liveness_proto_depIdxs = []int32{
	1, // 0: saga.v1.WorkerEvent.start:type_name -> saga.v1.StartJob
	2, // 1: saga.v1.WorkerEvent.heartbeat:type_name -> saga.v1.Heartbeat
	3, // 2: saga.v1.WorkerEvent.complete:type_name -> saga.v1.Complete
	4, // 3: saga.v1.WorkerEvent.error:type_name -> saga.v1.Error
	6, // 4: saga.v1.EngineEvent.ack:type_name -> saga.v1.Acknowledged
	7, // 5: saga.v1.EngineEvent.cancel:type_name -> saga.v1.CancelRequested
	0, // 6: saga.v1.WorkerLiveness.ExecuteStep:input_type -> saga.v1.WorkerEvent
	5, // 7: saga.v1.WorkerLiveness.ExecuteStep:output_type -> saga.v1.EngineEvent
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_liveness_proto_init() }
func file_proto_liveness_proto_init() {
	if File_proto_liveness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_liveness_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StartJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Complete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EngineEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Acknowledged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_liveness_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CancelRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_liveness_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerEvent_Start)(nil),
		(*WorkerEvent_Heartbeat)(nil),
		(*WorkerEvent_Complete)(nil),
		(*WorkerEvent_Error)(nil),
	}
	file_proto_liveness_proto_msgTypes[5].OneofWrappers = []any{
		(*EngineEvent_Ack)(nil),
		(*EngineEvent_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_liveness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_liveness_proto_goTypes,
		DependencyIndexes: file_proto_liveness_proto_depIdxs,
		MessageInfos:      file_proto_liveness_proto_msgTypes,
	}.Build()
	File_proto_liveness_proto = out.File
	file_proto_liveness_proto_rawDesc = nil
	file_proto_liveness_proto_goTypes = nil
	file_proto_liveness_proto_depIdxs = nil
}
